//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace EntidadesCampanasPPG.Modelo
{    
    public partial class Cronograma
    {
        public int ID { get; set; }
        public int IDCampania { get; set; }
        public int IDPadre { get; set; }
        public bool Padre { get; set; }
        public int IDTarea { get; set; }
        public string Actividad { get; set; }
        public decimal Duracion { get; set; }
        public DateTime FechaInicio { get; set; }
        public string StrFechaInicio { get; set; }
        public DateTime FechaFin { get; set; }
        public string StrFechaFin { get; set; }
        public DateTime FechaInicioReal { get; set; }
        public string StrFechaInicioReal { get; set; }
        public DateTime FechaFinReal { get; set; }
        public string StrFechaFinReal { get; set; }
        public int TiempoOptimista { get; set; }
        public int TiempoPesimista { get; set; }
        public DateTime FechaHoy { get; set; }
        public string StrFechaHoy { get; set; }
        public string PPGID { get; set; }
        public string NombreResponsable { get; set; }
        public string Correo { get; set; }
        public string PPGID_2 { get; set; }
        public string NombreResponsable_2 { get; set; }
        public string Correo_2 { get; set; }
        public string Comentario { get; set; }
        public decimal PorcentajeSistema { get; set; }
        public decimal PorcentajeUsuario { get; set; }
        public decimal PorcentajeUsuarioEsfuerzo { get; set; } 
        public decimal PorcentajeSistemaReal { get; set; }
        public decimal PorcentajeDiferencia { get; set; }
        public DateTime FechaCreacion { get; set; }
        public string StrFechaCreacion { get; set; }
        public DateTime FechaModificacion { get; set; }
        public string StrFechaModificacion { get; set; }
        public string Predecesor { get; set; }
        public int VersionCronograma { get; set; }
        public string IdTreePadre { get; set; }
        public string UsuarioCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string TipoFlujo { get; set; }
        public int IdTipoFlujo { get; set; }
        public int EstatusEnvio { get; set; }
        public string Incluir { get; set; }
        public int IdIncluir { get; set; }
        public string ValidarDatos { get; set; }
        public string ValidarPredecesor { get; set; }
        public string ValidarFecha { get; set; }
        public string ValidarFechaProgramada { get; set; }
        public string ValidarFechaVsActual { get; set; }
        public bool Update { get; set; }
    }
}
