//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallWCFCampanaJSON.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Campana", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCampanasPPG.Modelo")]
    [System.SerializableAttribute()]
    public partial class Campana : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CampaExpressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientesOtrosCanalesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExcMecanicasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaFinPublicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaFinSubCanalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaInicioPublicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaInicioSubCanalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAlcanceTerritorialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdNegocioLiderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSubcanalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoCampaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoSellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JustificacionNCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CallWCFCampanaJSON.ServiceReference1.Kroma KromaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LiderCampaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CallWCFCampanaJSON.ServiceReference1.Producto[] ListaProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CallWCFCampanaJSON.ServiceReference1.Publicidad[] ListaPublicidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCampaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjetivoNCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObsPublicidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PPGIDLiderCampaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PPGIDRegistraCampaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistraCampaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CampaExpress {
            get {
                return this.CampaExpressField;
            }
            set {
                if ((this.CampaExpressField.Equals(value) != true)) {
                    this.CampaExpressField = value;
                    this.RaisePropertyChanged("CampaExpress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientesOtrosCanales {
            get {
                return this.ClientesOtrosCanalesField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientesOtrosCanalesField, value) != true)) {
                    this.ClientesOtrosCanalesField = value;
                    this.RaisePropertyChanged("ClientesOtrosCanales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExcMecanicas {
            get {
                return this.ExcMecanicasField;
            }
            set {
                if ((object.ReferenceEquals(this.ExcMecanicasField, value) != true)) {
                    this.ExcMecanicasField = value;
                    this.RaisePropertyChanged("ExcMecanicas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaDocumento {
            get {
                return this.FechaDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaDocumentoField, value) != true)) {
                    this.FechaDocumentoField = value;
                    this.RaisePropertyChanged("FechaDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaFinPublico {
            get {
                return this.FechaFinPublicoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaFinPublicoField, value) != true)) {
                    this.FechaFinPublicoField = value;
                    this.RaisePropertyChanged("FechaFinPublico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaFinSubCanal {
            get {
                return this.FechaFinSubCanalField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaFinSubCanalField, value) != true)) {
                    this.FechaFinSubCanalField = value;
                    this.RaisePropertyChanged("FechaFinSubCanal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaInicioPublico {
            get {
                return this.FechaInicioPublicoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaInicioPublicoField, value) != true)) {
                    this.FechaInicioPublicoField = value;
                    this.RaisePropertyChanged("FechaInicioPublico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaInicioSubCanal {
            get {
                return this.FechaInicioSubCanalField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaInicioSubCanalField, value) != true)) {
                    this.FechaInicioSubCanalField = value;
                    this.RaisePropertyChanged("FechaInicioSubCanal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAlcanceTerritorial {
            get {
                return this.IdAlcanceTerritorialField;
            }
            set {
                if ((this.IdAlcanceTerritorialField.Equals(value) != true)) {
                    this.IdAlcanceTerritorialField = value;
                    this.RaisePropertyChanged("IdAlcanceTerritorial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMoneda {
            get {
                return this.IdMonedaField;
            }
            set {
                if ((this.IdMonedaField.Equals(value) != true)) {
                    this.IdMonedaField = value;
                    this.RaisePropertyChanged("IdMoneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdNegocioLider {
            get {
                return this.IdNegocioLiderField;
            }
            set {
                if ((this.IdNegocioLiderField.Equals(value) != true)) {
                    this.IdNegocioLiderField = value;
                    this.RaisePropertyChanged("IdNegocioLider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSubcanal {
            get {
                return this.IdSubcanalField;
            }
            set {
                if ((this.IdSubcanalField.Equals(value) != true)) {
                    this.IdSubcanalField = value;
                    this.RaisePropertyChanged("IdSubcanal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoCampa {
            get {
                return this.IdTipoCampaField;
            }
            set {
                if ((this.IdTipoCampaField.Equals(value) != true)) {
                    this.IdTipoCampaField = value;
                    this.RaisePropertyChanged("IdTipoCampa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoSell {
            get {
                return this.IdTipoSellField;
            }
            set {
                if ((this.IdTipoSellField.Equals(value) != true)) {
                    this.IdTipoSellField = value;
                    this.RaisePropertyChanged("IdTipoSell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JustificacionNC {
            get {
                return this.JustificacionNCField;
            }
            set {
                if ((object.ReferenceEquals(this.JustificacionNCField, value) != true)) {
                    this.JustificacionNCField = value;
                    this.RaisePropertyChanged("JustificacionNC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CallWCFCampanaJSON.ServiceReference1.Kroma Kroma {
            get {
                return this.KromaField;
            }
            set {
                if ((object.ReferenceEquals(this.KromaField, value) != true)) {
                    this.KromaField = value;
                    this.RaisePropertyChanged("Kroma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LiderCampa {
            get {
                return this.LiderCampaField;
            }
            set {
                if ((object.ReferenceEquals(this.LiderCampaField, value) != true)) {
                    this.LiderCampaField = value;
                    this.RaisePropertyChanged("LiderCampa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CallWCFCampanaJSON.ServiceReference1.Producto[] ListaProducto {
            get {
                return this.ListaProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaProductoField, value) != true)) {
                    this.ListaProductoField = value;
                    this.RaisePropertyChanged("ListaProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CallWCFCampanaJSON.ServiceReference1.Publicidad[] ListaPublicidad {
            get {
                return this.ListaPublicidadField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaPublicidadField, value) != true)) {
                    this.ListaPublicidadField = value;
                    this.RaisePropertyChanged("ListaPublicidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCampa {
            get {
                return this.NombreCampaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCampaField, value) != true)) {
                    this.NombreCampaField = value;
                    this.RaisePropertyChanged("NombreCampa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjetivoNC {
            get {
                return this.ObjetivoNCField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjetivoNCField, value) != true)) {
                    this.ObjetivoNCField = value;
                    this.RaisePropertyChanged("ObjetivoNC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObsPublicidad {
            get {
                return this.ObsPublicidadField;
            }
            set {
                if ((object.ReferenceEquals(this.ObsPublicidadField, value) != true)) {
                    this.ObsPublicidadField = value;
                    this.RaisePropertyChanged("ObsPublicidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PPGIDLiderCampa {
            get {
                return this.PPGIDLiderCampaField;
            }
            set {
                if ((object.ReferenceEquals(this.PPGIDLiderCampaField, value) != true)) {
                    this.PPGIDLiderCampaField = value;
                    this.RaisePropertyChanged("PPGIDLiderCampa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PPGIDRegistraCampa {
            get {
                return this.PPGIDRegistraCampaField;
            }
            set {
                if ((object.ReferenceEquals(this.PPGIDRegistraCampaField, value) != true)) {
                    this.PPGIDRegistraCampaField = value;
                    this.RaisePropertyChanged("PPGIDRegistraCampa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistraCampa {
            get {
                return this.RegistraCampaField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistraCampaField, value) != true)) {
                    this.RegistraCampaField = value;
                    this.RaisePropertyChanged("RegistraCampa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kroma", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCampanasPPG.Modelo")]
    [System.SerializableAttribute()]
    public partial class Kroma : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DF17Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DF6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DF9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FronteraNorteMonterreyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdLineaAportacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JustificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RegionalOccidenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DF {
            get {
                return this.DFField;
            }
            set {
                if ((this.DFField.Equals(value) != true)) {
                    this.DFField = value;
                    this.RaisePropertyChanged("DF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DF17 {
            get {
                return this.DF17Field;
            }
            set {
                if ((this.DF17Field.Equals(value) != true)) {
                    this.DF17Field = value;
                    this.RaisePropertyChanged("DF17");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DF6 {
            get {
                return this.DF6Field;
            }
            set {
                if ((this.DF6Field.Equals(value) != true)) {
                    this.DF6Field = value;
                    this.RaisePropertyChanged("DF6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DF9 {
            get {
                return this.DF9Field;
            }
            set {
                if ((this.DF9Field.Equals(value) != true)) {
                    this.DF9Field = value;
                    this.RaisePropertyChanged("DF9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FronteraNorteMonterrey {
            get {
                return this.FronteraNorteMonterreyField;
            }
            set {
                if ((this.FronteraNorteMonterreyField.Equals(value) != true)) {
                    this.FronteraNorteMonterreyField = value;
                    this.RaisePropertyChanged("FronteraNorteMonterrey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLineaAportacion {
            get {
                return this.IdLineaAportacionField;
            }
            set {
                if ((this.IdLineaAportacionField.Equals(value) != true)) {
                    this.IdLineaAportacionField = value;
                    this.RaisePropertyChanged("IdLineaAportacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Justificacion {
            get {
                return this.JustificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.JustificacionField, value) != true)) {
                    this.JustificacionField = value;
                    this.RaisePropertyChanged("Justificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RegionalOccidente {
            get {
                return this.RegionalOccidenteField;
            }
            set {
                if ((this.RegionalOccidenteField.Equals(value) != true)) {
                    this.RegionalOccidenteField = value;
                    this.RaisePropertyChanged("RegionalOccidente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCampanasPPG.Modelo")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlcanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CantidadOdescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CapacidadProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFamiliaEstelarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdLineaProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMecanicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SistemaAplicacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Alcance {
            get {
                return this.AlcanceField;
            }
            set {
                if ((this.AlcanceField.Equals(value) != true)) {
                    this.AlcanceField = value;
                    this.RaisePropertyChanged("Alcance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CantidadOdescuento {
            get {
                return this.CantidadOdescuentoField;
            }
            set {
                if ((this.CantidadOdescuentoField.Equals(value) != true)) {
                    this.CantidadOdescuentoField = value;
                    this.RaisePropertyChanged("CantidadOdescuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CapacidadProducto {
            get {
                return this.CapacidadProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.CapacidadProductoField, value) != true)) {
                    this.CapacidadProductoField = value;
                    this.RaisePropertyChanged("CapacidadProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFamiliaEstelar {
            get {
                return this.IdFamiliaEstelarField;
            }
            set {
                if ((this.IdFamiliaEstelarField.Equals(value) != true)) {
                    this.IdFamiliaEstelarField = value;
                    this.RaisePropertyChanged("IdFamiliaEstelar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLineaProducto {
            get {
                return this.IdLineaProductoField;
            }
            set {
                if ((this.IdLineaProductoField.Equals(value) != true)) {
                    this.IdLineaProductoField = value;
                    this.RaisePropertyChanged("IdLineaProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMecanica {
            get {
                return this.IdMecanicaField;
            }
            set {
                if ((this.IdMecanicaField.Equals(value) != true)) {
                    this.IdMecanicaField = value;
                    this.RaisePropertyChanged("IdMecanica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoProducto {
            get {
                return this.IdTipoProductoField;
            }
            set {
                if ((this.IdTipoProductoField.Equals(value) != true)) {
                    this.IdTipoProductoField = value;
                    this.RaisePropertyChanged("IdTipoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SistemaAplicacion {
            get {
                return this.SistemaAplicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.SistemaAplicacionField, value) != true)) {
                    this.SistemaAplicacionField = value;
                    this.RaisePropertyChanged("SistemaAplicacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Publicidad", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCampanasPPG.Modelo")]
    [System.SerializableAttribute()]
    public partial class Publicidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPublicidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPublicidad {
            get {
                return this.IdPublicidadField;
            }
            set {
                if ((this.IdPublicidadField.Equals(value) != true)) {
                    this.IdPublicidadField = value;
                    this.RaisePropertyChanged("IdPublicidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServicioCampana")]
    public interface IServicioCampana {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCampana/GuardarCampana", ReplyAction="http://tempuri.org/IServicioCampana/GuardarCampanaResponse")]
        string GuardarCampana(CallWCFCampanaJSON.ServiceReference1.Campana Campana);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServicioCampana/GuardarCampana", ReplyAction="http://tempuri.org/IServicioCampana/GuardarCampanaResponse")]
        System.IAsyncResult BeginGuardarCampana(CallWCFCampanaJSON.ServiceReference1.Campana Campana, System.AsyncCallback callback, object asyncState);
        
        string EndGuardarCampana(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCampana/MostrarCampana", ReplyAction="http://tempuri.org/IServicioCampana/MostrarCampanaResponse")]
        CallWCFCampanaJSON.ServiceReference1.Campana MostrarCampana();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServicioCampana/MostrarCampana", ReplyAction="http://tempuri.org/IServicioCampana/MostrarCampanaResponse")]
        System.IAsyncResult BeginMostrarCampana(System.AsyncCallback callback, object asyncState);
        
        CallWCFCampanaJSON.ServiceReference1.Campana EndMostrarCampana(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioCampanaChannel : CallWCFCampanaJSON.ServiceReference1.IServicioCampana, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GuardarCampanaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GuardarCampanaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MostrarCampanaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public MostrarCampanaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CallWCFCampanaJSON.ServiceReference1.Campana Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CallWCFCampanaJSON.ServiceReference1.Campana)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCampanaClient : System.ServiceModel.ClientBase<CallWCFCampanaJSON.ServiceReference1.IServicioCampana>, CallWCFCampanaJSON.ServiceReference1.IServicioCampana {
        
        private BeginOperationDelegate onBeginGuardarCampanaDelegate;
        
        private EndOperationDelegate onEndGuardarCampanaDelegate;
        
        private System.Threading.SendOrPostCallback onGuardarCampanaCompletedDelegate;
        
        private BeginOperationDelegate onBeginMostrarCampanaDelegate;
        
        private EndOperationDelegate onEndMostrarCampanaDelegate;
        
        private System.Threading.SendOrPostCallback onMostrarCampanaCompletedDelegate;
        
        public ServicioCampanaClient() {
        }
        
        public ServicioCampanaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCampanaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCampanaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCampanaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GuardarCampanaCompletedEventArgs> GuardarCampanaCompleted;
        
        public event System.EventHandler<MostrarCampanaCompletedEventArgs> MostrarCampanaCompleted;
        
        public string GuardarCampana(CallWCFCampanaJSON.ServiceReference1.Campana Campana) {
            return base.Channel.GuardarCampana(Campana);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGuardarCampana(CallWCFCampanaJSON.ServiceReference1.Campana Campana, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGuardarCampana(Campana, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGuardarCampana(System.IAsyncResult result) {
            return base.Channel.EndGuardarCampana(result);
        }
        
        private System.IAsyncResult OnBeginGuardarCampana(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CallWCFCampanaJSON.ServiceReference1.Campana Campana = ((CallWCFCampanaJSON.ServiceReference1.Campana)(inValues[0]));
            return this.BeginGuardarCampana(Campana, callback, asyncState);
        }
        
        private object[] OnEndGuardarCampana(System.IAsyncResult result) {
            string retVal = this.EndGuardarCampana(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGuardarCampanaCompleted(object state) {
            if ((this.GuardarCampanaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GuardarCampanaCompleted(this, new GuardarCampanaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GuardarCampanaAsync(CallWCFCampanaJSON.ServiceReference1.Campana Campana) {
            this.GuardarCampanaAsync(Campana, null);
        }
        
        public void GuardarCampanaAsync(CallWCFCampanaJSON.ServiceReference1.Campana Campana, object userState) {
            if ((this.onBeginGuardarCampanaDelegate == null)) {
                this.onBeginGuardarCampanaDelegate = new BeginOperationDelegate(this.OnBeginGuardarCampana);
            }
            if ((this.onEndGuardarCampanaDelegate == null)) {
                this.onEndGuardarCampanaDelegate = new EndOperationDelegate(this.OnEndGuardarCampana);
            }
            if ((this.onGuardarCampanaCompletedDelegate == null)) {
                this.onGuardarCampanaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGuardarCampanaCompleted);
            }
            base.InvokeAsync(this.onBeginGuardarCampanaDelegate, new object[] {
                        Campana}, this.onEndGuardarCampanaDelegate, this.onGuardarCampanaCompletedDelegate, userState);
        }
        
        public CallWCFCampanaJSON.ServiceReference1.Campana MostrarCampana() {
            return base.Channel.MostrarCampana();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginMostrarCampana(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMostrarCampana(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public CallWCFCampanaJSON.ServiceReference1.Campana EndMostrarCampana(System.IAsyncResult result) {
            return base.Channel.EndMostrarCampana(result);
        }
        
        private System.IAsyncResult OnBeginMostrarCampana(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginMostrarCampana(callback, asyncState);
        }
        
        private object[] OnEndMostrarCampana(System.IAsyncResult result) {
            CallWCFCampanaJSON.ServiceReference1.Campana retVal = this.EndMostrarCampana(result);
            return new object[] {
                    retVal};
        }
        
        private void OnMostrarCampanaCompleted(object state) {
            if ((this.MostrarCampanaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.MostrarCampanaCompleted(this, new MostrarCampanaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void MostrarCampanaAsync() {
            this.MostrarCampanaAsync(null);
        }
        
        public void MostrarCampanaAsync(object userState) {
            if ((this.onBeginMostrarCampanaDelegate == null)) {
                this.onBeginMostrarCampanaDelegate = new BeginOperationDelegate(this.OnBeginMostrarCampana);
            }
            if ((this.onEndMostrarCampanaDelegate == null)) {
                this.onEndMostrarCampanaDelegate = new EndOperationDelegate(this.OnEndMostrarCampana);
            }
            if ((this.onMostrarCampanaCompletedDelegate == null)) {
                this.onMostrarCampanaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMostrarCampanaCompleted);
            }
            base.InvokeAsync(this.onBeginMostrarCampanaDelegate, null, this.onEndMostrarCampanaDelegate, this.onMostrarCampanaCompletedDelegate, userState);
        }
    }
}
